@url_dev=http://localhost:3056/v1/api

### sign up

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: test

{
    "name": "haphuthinh123",
    "email": "haphuthinh3320022212@gmail.com",
    "password": "haphuthinh"
}